// Code generated by Kitex v0.13.1. DO NOT EDIT.

package apiservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "user_service/api/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newApiServiceRegisterArgs,
		newApiServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newApiServiceLoginArgs,
		newApiServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OAuth2Login": kitex.NewMethodInfo(
		oAuth2LoginHandler,
		newApiServiceOAuth2LoginArgs,
		newApiServiceOAuth2LoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newApiServiceGetUserInfoArgs,
		newApiServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newApiServiceUpdateUserInfoArgs,
		newApiServiceUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPassword": kitex.NewMethodInfo(
		resetPasswordHandler,
		newApiServiceResetPasswordArgs,
		newApiServiceResetPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newApiServiceRefreshTokenArgs,
		newApiServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	apiServiceServiceInfo                = NewServiceInfo()
	apiServiceServiceInfoForClient       = NewServiceInfoForClient()
	apiServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return apiServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return apiServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return apiServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ApiService"
	handlerType := (*api.ApiService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName":     "api",
		"ServiceFilePath": `D:\GoProj\user_service\api\idl\api.thrift`,
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceRegisterArgs)
	realResult := result.(*api.ApiServiceRegisterResult)
	success, err := handler.(api.ApiService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceRegisterArgs() interface{} {
	return api.NewApiServiceRegisterArgs()
}

func newApiServiceRegisterResult() interface{} {
	return api.NewApiServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceLoginArgs)
	realResult := result.(*api.ApiServiceLoginResult)
	success, err := handler.(api.ApiService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceLoginArgs() interface{} {
	return api.NewApiServiceLoginArgs()
}

func newApiServiceLoginResult() interface{} {
	return api.NewApiServiceLoginResult()
}

func oAuth2LoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceOAuth2LoginArgs)
	realResult := result.(*api.ApiServiceOAuth2LoginResult)
	success, err := handler.(api.ApiService).OAuth2Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceOAuth2LoginArgs() interface{} {
	return api.NewApiServiceOAuth2LoginArgs()
}

func newApiServiceOAuth2LoginResult() interface{} {
	return api.NewApiServiceOAuth2LoginResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceGetUserInfoArgs)
	realResult := result.(*api.ApiServiceGetUserInfoResult)
	success, err := handler.(api.ApiService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceGetUserInfoArgs() interface{} {
	return api.NewApiServiceGetUserInfoArgs()
}

func newApiServiceGetUserInfoResult() interface{} {
	return api.NewApiServiceGetUserInfoResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceUpdateUserInfoArgs)
	realResult := result.(*api.ApiServiceUpdateUserInfoResult)
	success, err := handler.(api.ApiService).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceUpdateUserInfoArgs() interface{} {
	return api.NewApiServiceUpdateUserInfoArgs()
}

func newApiServiceUpdateUserInfoResult() interface{} {
	return api.NewApiServiceUpdateUserInfoResult()
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceResetPasswordArgs)
	realResult := result.(*api.ApiServiceResetPasswordResult)
	success, err := handler.(api.ApiService).ResetPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceResetPasswordArgs() interface{} {
	return api.NewApiServiceResetPasswordArgs()
}

func newApiServiceResetPasswordResult() interface{} {
	return api.NewApiServiceResetPasswordResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiServiceRefreshTokenArgs)
	realResult := result.(*api.ApiServiceRefreshTokenResult)
	success, err := handler.(api.ApiService).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiServiceRefreshTokenArgs() interface{} {
	return api.NewApiServiceRefreshTokenArgs()
}

func newApiServiceRefreshTokenResult() interface{} {
	return api.NewApiServiceRefreshTokenResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *api.RegisterRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceRegisterArgs
	_args.Req = req
	var _result api.ApiServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *api.LoginRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceLoginArgs
	_args.Req = req
	var _result api.ApiServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OAuth2Login(ctx context.Context, req *api.OAuth2LoginRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceOAuth2LoginArgs
	_args.Req = req
	var _result api.ApiServiceOAuth2LoginResult
	if err = p.c.Call(ctx, "OAuth2Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *api.GetUserInfoRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceGetUserInfoArgs
	_args.Req = req
	var _result api.ApiServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *api.UpdateUserInfoRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceUpdateUserInfoArgs
	_args.Req = req
	var _result api.ApiServiceUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPassword(ctx context.Context, req *api.ResetPasswordRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceResetPasswordArgs
	_args.Req = req
	var _result api.ApiServiceResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *api.RefreshTokenRequest) (r *api.BaseResponse, err error) {
	var _args api.ApiServiceRefreshTokenArgs
	_args.Req = req
	var _result api.ApiServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
