// Code generated by Kitex v0.13.1. DO NOT EDIT.

package apiservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "user_service/api/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *api.RegisterRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
	Login(ctx context.Context, req *api.LoginRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
	OAuth2Login(ctx context.Context, req *api.OAuth2LoginRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
	GetUserInfo(ctx context.Context, req *api.GetUserInfoRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
	UpdateUserInfo(ctx context.Context, req *api.UpdateUserInfoRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
	ResetPassword(ctx context.Context, req *api.ResetPasswordRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
	RefreshToken(ctx context.Context, req *api.RefreshTokenRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kApiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kApiServiceClient struct {
	*kClient
}

func (p *kApiServiceClient) Register(ctx context.Context, req *api.RegisterRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kApiServiceClient) Login(ctx context.Context, req *api.LoginRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kApiServiceClient) OAuth2Login(ctx context.Context, req *api.OAuth2LoginRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.OAuth2Login(ctx, req)
}

func (p *kApiServiceClient) GetUserInfo(ctx context.Context, req *api.GetUserInfoRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kApiServiceClient) UpdateUserInfo(ctx context.Context, req *api.UpdateUserInfoRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, req)
}

func (p *kApiServiceClient) ResetPassword(ctx context.Context, req *api.ResetPasswordRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetPassword(ctx, req)
}

func (p *kApiServiceClient) RefreshToken(ctx context.Context, req *api.RefreshTokenRequest, callOptions ...callopt.Option) (r *api.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, req)
}
