// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
)

type TokenInfo struct {
	AccessToken  string `thrift:"access_token,1" frugal:"1,default,string" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" frugal:"2,default,string" json:"refresh_token"`
	ExpiresIn    int64  `thrift:"expires_in,3" frugal:"3,default,i64" json:"expires_in"`
	TokenType    string `thrift:"token_type,4" frugal:"4,default,string" json:"token_type"`
}

func NewTokenInfo() *TokenInfo {
	return &TokenInfo{}
}

func (p *TokenInfo) InitDefault() {
}

func (p *TokenInfo) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *TokenInfo) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *TokenInfo) GetExpiresIn() (v int64) {
	return p.ExpiresIn
}

func (p *TokenInfo) GetTokenType() (v string) {
	return p.TokenType
}
func (p *TokenInfo) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *TokenInfo) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *TokenInfo) SetExpiresIn(val int64) {
	p.ExpiresIn = val
}
func (p *TokenInfo) SetTokenType(val string) {
	p.TokenType = val
}

func (p *TokenInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TokenInfo(%+v)", *p)
}

var fieldIDToName_TokenInfo = map[int16]string{
	1: "access_token",
	2: "refresh_token",
	3: "expires_in",
	4: "token_type",
}

type ValidateTokenRequest struct {
	Token string `thrift:"token,1" frugal:"1,default,string" json:"token"`
}

func NewValidateTokenRequest() *ValidateTokenRequest {
	return &ValidateTokenRequest{}
}

func (p *ValidateTokenRequest) InitDefault() {
}

func (p *ValidateTokenRequest) GetToken() (v string) {
	return p.Token
}
func (p *ValidateTokenRequest) SetToken(val string) {
	p.Token = val
}

func (p *ValidateTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateTokenRequest(%+v)", *p)
}

var fieldIDToName_ValidateTokenRequest = map[int16]string{
	1: "token",
}

type ValidateTokenResponse struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	IsValid bool   `thrift:"is_valid,3" frugal:"3,default,bool" json:"is_valid"`
	UserId  int64  `thrift:"user_id,4" frugal:"4,default,i64" json:"user_id"`
}

func NewValidateTokenResponse() *ValidateTokenResponse {
	return &ValidateTokenResponse{}
}

func (p *ValidateTokenResponse) InitDefault() {
}

func (p *ValidateTokenResponse) GetCode() (v int32) {
	return p.Code
}

func (p *ValidateTokenResponse) GetMessage() (v string) {
	return p.Message
}

func (p *ValidateTokenResponse) GetIsValid() (v bool) {
	return p.IsValid
}

func (p *ValidateTokenResponse) GetUserId() (v int64) {
	return p.UserId
}
func (p *ValidateTokenResponse) SetCode(val int32) {
	p.Code = val
}
func (p *ValidateTokenResponse) SetMessage(val string) {
	p.Message = val
}
func (p *ValidateTokenResponse) SetIsValid(val bool) {
	p.IsValid = val
}
func (p *ValidateTokenResponse) SetUserId(val int64) {
	p.UserId = val
}

func (p *ValidateTokenResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateTokenResponse(%+v)", *p)
}

var fieldIDToName_ValidateTokenResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "is_valid",
	4: "user_id",
}

type RefreshTokenRequest struct {
	RefreshToken string `thrift:"refresh_token,1" frugal:"1,default,string" json:"refresh_token"`
}

func NewRefreshTokenRequest() *RefreshTokenRequest {
	return &RefreshTokenRequest{}
}

func (p *RefreshTokenRequest) InitDefault() {
}

func (p *RefreshTokenRequest) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *RefreshTokenRequest) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *RefreshTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenRequest(%+v)", *p)
}

var fieldIDToName_RefreshTokenRequest = map[int16]string{
	1: "refresh_token",
}

type RefreshTokenResponse struct {
	Code      int32      `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message   string     `thrift:"message,2" frugal:"2,default,string" json:"message"`
	TokenInfo *TokenInfo `thrift:"token_info,3" frugal:"3,default,TokenInfo" json:"token_info"`
}

func NewRefreshTokenResponse() *RefreshTokenResponse {
	return &RefreshTokenResponse{}
}

func (p *RefreshTokenResponse) InitDefault() {
}

func (p *RefreshTokenResponse) GetCode() (v int32) {
	return p.Code
}

func (p *RefreshTokenResponse) GetMessage() (v string) {
	return p.Message
}

var RefreshTokenResponse_TokenInfo_DEFAULT *TokenInfo

func (p *RefreshTokenResponse) GetTokenInfo() (v *TokenInfo) {
	if !p.IsSetTokenInfo() {
		return RefreshTokenResponse_TokenInfo_DEFAULT
	}
	return p.TokenInfo
}
func (p *RefreshTokenResponse) SetCode(val int32) {
	p.Code = val
}
func (p *RefreshTokenResponse) SetMessage(val string) {
	p.Message = val
}
func (p *RefreshTokenResponse) SetTokenInfo(val *TokenInfo) {
	p.TokenInfo = val
}

func (p *RefreshTokenResponse) IsSetTokenInfo() bool {
	return p.TokenInfo != nil
}

func (p *RefreshTokenResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenResponse(%+v)", *p)
}

var fieldIDToName_RefreshTokenResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "token_info",
}

type OAuth2LoginRequest struct {
	Provider    string `thrift:"provider,1" frugal:"1,default,string" json:"provider"`
	Code        string `thrift:"code,2" frugal:"2,default,string" json:"code"`
	RedirectUri string `thrift:"redirect_uri,3" frugal:"3,default,string" json:"redirect_uri"`
}

func NewOAuth2LoginRequest() *OAuth2LoginRequest {
	return &OAuth2LoginRequest{}
}

func (p *OAuth2LoginRequest) InitDefault() {
}

func (p *OAuth2LoginRequest) GetProvider() (v string) {
	return p.Provider
}

func (p *OAuth2LoginRequest) GetCode() (v string) {
	return p.Code
}

func (p *OAuth2LoginRequest) GetRedirectUri() (v string) {
	return p.RedirectUri
}
func (p *OAuth2LoginRequest) SetProvider(val string) {
	p.Provider = val
}
func (p *OAuth2LoginRequest) SetCode(val string) {
	p.Code = val
}
func (p *OAuth2LoginRequest) SetRedirectUri(val string) {
	p.RedirectUri = val
}

func (p *OAuth2LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAuth2LoginRequest(%+v)", *p)
}

var fieldIDToName_OAuth2LoginRequest = map[int16]string{
	1: "provider",
	2: "code",
	3: "redirect_uri",
}

type OAuth2LoginResponse struct {
	Code      int32      `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message   string     `thrift:"message,2" frugal:"2,default,string" json:"message"`
	TokenInfo *TokenInfo `thrift:"token_info,3" frugal:"3,default,TokenInfo" json:"token_info"`
	UserId    int64      `thrift:"user_id,4" frugal:"4,default,i64" json:"user_id"`
	IsNewUser bool       `thrift:"is_new_user,5" frugal:"5,default,bool" json:"is_new_user"`
}

func NewOAuth2LoginResponse() *OAuth2LoginResponse {
	return &OAuth2LoginResponse{}
}

func (p *OAuth2LoginResponse) InitDefault() {
}

func (p *OAuth2LoginResponse) GetCode() (v int32) {
	return p.Code
}

func (p *OAuth2LoginResponse) GetMessage() (v string) {
	return p.Message
}

var OAuth2LoginResponse_TokenInfo_DEFAULT *TokenInfo

func (p *OAuth2LoginResponse) GetTokenInfo() (v *TokenInfo) {
	if !p.IsSetTokenInfo() {
		return OAuth2LoginResponse_TokenInfo_DEFAULT
	}
	return p.TokenInfo
}

func (p *OAuth2LoginResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *OAuth2LoginResponse) GetIsNewUser() (v bool) {
	return p.IsNewUser
}
func (p *OAuth2LoginResponse) SetCode(val int32) {
	p.Code = val
}
func (p *OAuth2LoginResponse) SetMessage(val string) {
	p.Message = val
}
func (p *OAuth2LoginResponse) SetTokenInfo(val *TokenInfo) {
	p.TokenInfo = val
}
func (p *OAuth2LoginResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *OAuth2LoginResponse) SetIsNewUser(val bool) {
	p.IsNewUser = val
}

func (p *OAuth2LoginResponse) IsSetTokenInfo() bool {
	return p.TokenInfo != nil
}

func (p *OAuth2LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAuth2LoginResponse(%+v)", *p)
}

var fieldIDToName_OAuth2LoginResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "token_info",
	4: "user_id",
	5: "is_new_user",
}

type AuthService interface {
	ValidateToken(ctx context.Context, req *ValidateTokenRequest) (r *ValidateTokenResponse, err error)

	RefreshToken(ctx context.Context, req *RefreshTokenRequest) (r *RefreshTokenResponse, err error)

	OAuth2Login(ctx context.Context, req *OAuth2LoginRequest) (r *OAuth2LoginResponse, err error)
}

type AuthServiceValidateTokenArgs struct {
	Req *ValidateTokenRequest `thrift:"req,1" frugal:"1,default,ValidateTokenRequest" json:"req"`
}

func NewAuthServiceValidateTokenArgs() *AuthServiceValidateTokenArgs {
	return &AuthServiceValidateTokenArgs{}
}

func (p *AuthServiceValidateTokenArgs) InitDefault() {
}

var AuthServiceValidateTokenArgs_Req_DEFAULT *ValidateTokenRequest

func (p *AuthServiceValidateTokenArgs) GetReq() (v *ValidateTokenRequest) {
	if !p.IsSetReq() {
		return AuthServiceValidateTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceValidateTokenArgs) SetReq(val *ValidateTokenRequest) {
	p.Req = val
}

func (p *AuthServiceValidateTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceValidateTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateTokenArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateTokenArgs = map[int16]string{
	1: "req",
}

type AuthServiceValidateTokenResult struct {
	Success *ValidateTokenResponse `thrift:"success,0,optional" frugal:"0,optional,ValidateTokenResponse" json:"success,omitempty"`
}

func NewAuthServiceValidateTokenResult() *AuthServiceValidateTokenResult {
	return &AuthServiceValidateTokenResult{}
}

func (p *AuthServiceValidateTokenResult) InitDefault() {
}

var AuthServiceValidateTokenResult_Success_DEFAULT *ValidateTokenResponse

func (p *AuthServiceValidateTokenResult) GetSuccess() (v *ValidateTokenResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceValidateTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceValidateTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*ValidateTokenResponse)
}

func (p *AuthServiceValidateTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceValidateTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateTokenResult(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateTokenResult = map[int16]string{
	0: "success",
}

type AuthServiceRefreshTokenArgs struct {
	Req *RefreshTokenRequest `thrift:"req,1" frugal:"1,default,RefreshTokenRequest" json:"req"`
}

func NewAuthServiceRefreshTokenArgs() *AuthServiceRefreshTokenArgs {
	return &AuthServiceRefreshTokenArgs{}
}

func (p *AuthServiceRefreshTokenArgs) InitDefault() {
}

var AuthServiceRefreshTokenArgs_Req_DEFAULT *RefreshTokenRequest

func (p *AuthServiceRefreshTokenArgs) GetReq() (v *RefreshTokenRequest) {
	if !p.IsSetReq() {
		return AuthServiceRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceRefreshTokenArgs) SetReq(val *RefreshTokenRequest) {
	p.Req = val
}

func (p *AuthServiceRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRefreshTokenArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceRefreshTokenArgs = map[int16]string{
	1: "req",
}

type AuthServiceRefreshTokenResult struct {
	Success *RefreshTokenResponse `thrift:"success,0,optional" frugal:"0,optional,RefreshTokenResponse" json:"success,omitempty"`
}

func NewAuthServiceRefreshTokenResult() *AuthServiceRefreshTokenResult {
	return &AuthServiceRefreshTokenResult{}
}

func (p *AuthServiceRefreshTokenResult) InitDefault() {
}

var AuthServiceRefreshTokenResult_Success_DEFAULT *RefreshTokenResponse

func (p *AuthServiceRefreshTokenResult) GetSuccess() (v *RefreshTokenResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshTokenResponse)
}

func (p *AuthServiceRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRefreshTokenResult(%+v)", *p)
}

var fieldIDToName_AuthServiceRefreshTokenResult = map[int16]string{
	0: "success",
}

type AuthServiceOAuth2LoginArgs struct {
	Req *OAuth2LoginRequest `thrift:"req,1" frugal:"1,default,OAuth2LoginRequest" json:"req"`
}

func NewAuthServiceOAuth2LoginArgs() *AuthServiceOAuth2LoginArgs {
	return &AuthServiceOAuth2LoginArgs{}
}

func (p *AuthServiceOAuth2LoginArgs) InitDefault() {
}

var AuthServiceOAuth2LoginArgs_Req_DEFAULT *OAuth2LoginRequest

func (p *AuthServiceOAuth2LoginArgs) GetReq() (v *OAuth2LoginRequest) {
	if !p.IsSetReq() {
		return AuthServiceOAuth2LoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceOAuth2LoginArgs) SetReq(val *OAuth2LoginRequest) {
	p.Req = val
}

func (p *AuthServiceOAuth2LoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceOAuth2LoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceOAuth2LoginArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceOAuth2LoginArgs = map[int16]string{
	1: "req",
}

type AuthServiceOAuth2LoginResult struct {
	Success *OAuth2LoginResponse `thrift:"success,0,optional" frugal:"0,optional,OAuth2LoginResponse" json:"success,omitempty"`
}

func NewAuthServiceOAuth2LoginResult() *AuthServiceOAuth2LoginResult {
	return &AuthServiceOAuth2LoginResult{}
}

func (p *AuthServiceOAuth2LoginResult) InitDefault() {
}

var AuthServiceOAuth2LoginResult_Success_DEFAULT *OAuth2LoginResponse

func (p *AuthServiceOAuth2LoginResult) GetSuccess() (v *OAuth2LoginResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceOAuth2LoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceOAuth2LoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*OAuth2LoginResponse)
}

func (p *AuthServiceOAuth2LoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceOAuth2LoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceOAuth2LoginResult(%+v)", *p)
}

var fieldIDToName_AuthServiceOAuth2LoginResult = map[int16]string{
	0: "success",
}
