// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
)

type BaseResponse struct {
	Code    int32             `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string            `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Data    map[string]string `thrift:"data,3,optional" frugal:"3,optional,map<string:string>" json:"data,omitempty"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResponse) GetMessage() (v string) {
	return p.Message
}

var BaseResponse_Data_DEFAULT map[string]string

func (p *BaseResponse) GetData() (v map[string]string) {
	if !p.IsSetData() {
		return BaseResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *BaseResponse) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResponse) SetMessage(val string) {
	p.Message = val
}
func (p *BaseResponse) SetData(val map[string]string) {
	p.Data = val
}

func (p *BaseResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

var fieldIDToName_BaseResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "data",
}

type RegisterRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Email    string `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Phone    string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterRequest) GetPhone() (v string) {
	return p.Phone
}
func (p *RegisterRequest) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterRequest) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterRequest) SetPhone(val string) {
	p.Phone = val
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "username",
	2: "password",
	3: "email",
	4: "phone",
}

type LoginRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "username",
	2: "password",
}

type OAuth2LoginRequest struct {
	Provider    string `thrift:"provider,1" frugal:"1,default,string" json:"provider"`
	Code        string `thrift:"code,2" frugal:"2,default,string" json:"code"`
	RedirectUri string `thrift:"redirect_uri,3" frugal:"3,default,string" json:"redirect_uri"`
}

func NewOAuth2LoginRequest() *OAuth2LoginRequest {
	return &OAuth2LoginRequest{}
}

func (p *OAuth2LoginRequest) InitDefault() {
}

func (p *OAuth2LoginRequest) GetProvider() (v string) {
	return p.Provider
}

func (p *OAuth2LoginRequest) GetCode() (v string) {
	return p.Code
}

func (p *OAuth2LoginRequest) GetRedirectUri() (v string) {
	return p.RedirectUri
}
func (p *OAuth2LoginRequest) SetProvider(val string) {
	p.Provider = val
}
func (p *OAuth2LoginRequest) SetCode(val string) {
	p.Code = val
}
func (p *OAuth2LoginRequest) SetRedirectUri(val string) {
	p.RedirectUri = val
}

func (p *OAuth2LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAuth2LoginRequest(%+v)", *p)
}

var fieldIDToName_OAuth2LoginRequest = map[int16]string{
	1: "provider",
	2: "code",
	3: "redirect_uri",
}

type GetUserInfoRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserInfoRequest() *GetUserInfoRequest {
	return &GetUserInfoRequest{}
}

func (p *GetUserInfoRequest) InitDefault() {
}

func (p *GetUserInfoRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInfoRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoRequest(%+v)", *p)
}

var fieldIDToName_GetUserInfoRequest = map[int16]string{
	1: "user_id",
}

type UpdateUserInfoRequest struct {
	UserId   int64   `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Username *string `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Email    *string `thrift:"email,3,optional" frugal:"3,optional,string" json:"email,omitempty"`
	Phone    *string `thrift:"phone,4,optional" frugal:"4,optional,string" json:"phone,omitempty"`
	Avatar   *string `thrift:"avatar,5,optional" frugal:"5,optional,string" json:"avatar,omitempty"`
	RealName *string `thrift:"real_name,6,optional" frugal:"6,optional,string" json:"real_name,omitempty"`
	Gender   *string `thrift:"gender,7,optional" frugal:"7,optional,string" json:"gender,omitempty"`
	Birthday *string `thrift:"birthday,8,optional" frugal:"8,optional,string" json:"birthday,omitempty"`
	Address  *string `thrift:"address,9,optional" frugal:"9,optional,string" json:"address,omitempty"`
	Bio      *string `thrift:"bio,10,optional" frugal:"10,optional,string" json:"bio,omitempty"`
}

func NewUpdateUserInfoRequest() *UpdateUserInfoRequest {
	return &UpdateUserInfoRequest{}
}

func (p *UpdateUserInfoRequest) InitDefault() {
}

func (p *UpdateUserInfoRequest) GetUserId() (v int64) {
	return p.UserId
}

var UpdateUserInfoRequest_Username_DEFAULT string

func (p *UpdateUserInfoRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UpdateUserInfoRequest_Username_DEFAULT
	}
	return *p.Username
}

var UpdateUserInfoRequest_Email_DEFAULT string

func (p *UpdateUserInfoRequest) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UpdateUserInfoRequest_Email_DEFAULT
	}
	return *p.Email
}

var UpdateUserInfoRequest_Phone_DEFAULT string

func (p *UpdateUserInfoRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UpdateUserInfoRequest_Phone_DEFAULT
	}
	return *p.Phone
}

var UpdateUserInfoRequest_Avatar_DEFAULT string

func (p *UpdateUserInfoRequest) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return UpdateUserInfoRequest_Avatar_DEFAULT
	}
	return *p.Avatar
}

var UpdateUserInfoRequest_RealName_DEFAULT string

func (p *UpdateUserInfoRequest) GetRealName() (v string) {
	if !p.IsSetRealName() {
		return UpdateUserInfoRequest_RealName_DEFAULT
	}
	return *p.RealName
}

var UpdateUserInfoRequest_Gender_DEFAULT string

func (p *UpdateUserInfoRequest) GetGender() (v string) {
	if !p.IsSetGender() {
		return UpdateUserInfoRequest_Gender_DEFAULT
	}
	return *p.Gender
}

var UpdateUserInfoRequest_Birthday_DEFAULT string

func (p *UpdateUserInfoRequest) GetBirthday() (v string) {
	if !p.IsSetBirthday() {
		return UpdateUserInfoRequest_Birthday_DEFAULT
	}
	return *p.Birthday
}

var UpdateUserInfoRequest_Address_DEFAULT string

func (p *UpdateUserInfoRequest) GetAddress() (v string) {
	if !p.IsSetAddress() {
		return UpdateUserInfoRequest_Address_DEFAULT
	}
	return *p.Address
}

var UpdateUserInfoRequest_Bio_DEFAULT string

func (p *UpdateUserInfoRequest) GetBio() (v string) {
	if !p.IsSetBio() {
		return UpdateUserInfoRequest_Bio_DEFAULT
	}
	return *p.Bio
}
func (p *UpdateUserInfoRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateUserInfoRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *UpdateUserInfoRequest) SetEmail(val *string) {
	p.Email = val
}
func (p *UpdateUserInfoRequest) SetPhone(val *string) {
	p.Phone = val
}
func (p *UpdateUserInfoRequest) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *UpdateUserInfoRequest) SetRealName(val *string) {
	p.RealName = val
}
func (p *UpdateUserInfoRequest) SetGender(val *string) {
	p.Gender = val
}
func (p *UpdateUserInfoRequest) SetBirthday(val *string) {
	p.Birthday = val
}
func (p *UpdateUserInfoRequest) SetAddress(val *string) {
	p.Address = val
}
func (p *UpdateUserInfoRequest) SetBio(val *string) {
	p.Bio = val
}

func (p *UpdateUserInfoRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UpdateUserInfoRequest) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UpdateUserInfoRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UpdateUserInfoRequest) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *UpdateUserInfoRequest) IsSetRealName() bool {
	return p.RealName != nil
}

func (p *UpdateUserInfoRequest) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UpdateUserInfoRequest) IsSetBirthday() bool {
	return p.Birthday != nil
}

func (p *UpdateUserInfoRequest) IsSetAddress() bool {
	return p.Address != nil
}

func (p *UpdateUserInfoRequest) IsSetBio() bool {
	return p.Bio != nil
}

func (p *UpdateUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoRequest = map[int16]string{
	1:  "user_id",
	2:  "username",
	3:  "email",
	4:  "phone",
	5:  "avatar",
	6:  "real_name",
	7:  "gender",
	8:  "birthday",
	9:  "address",
	10: "bio",
}

type ResetPasswordRequest struct {
	UserId       int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	OldPassword  string `thrift:"old_password,2" frugal:"2,default,string" json:"old_password"`
	NewPassword_ string `thrift:"new_password,3" frugal:"3,default,string" json:"new_password"`
}

func NewResetPasswordRequest() *ResetPasswordRequest {
	return &ResetPasswordRequest{}
}

func (p *ResetPasswordRequest) InitDefault() {
}

func (p *ResetPasswordRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ResetPasswordRequest) GetOldPassword() (v string) {
	return p.OldPassword
}

func (p *ResetPasswordRequest) GetNewPassword_() (v string) {
	return p.NewPassword_
}
func (p *ResetPasswordRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ResetPasswordRequest) SetOldPassword(val string) {
	p.OldPassword = val
}
func (p *ResetPasswordRequest) SetNewPassword_(val string) {
	p.NewPassword_ = val
}

func (p *ResetPasswordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordRequest(%+v)", *p)
}

var fieldIDToName_ResetPasswordRequest = map[int16]string{
	1: "user_id",
	2: "old_password",
	3: "new_password",
}

type RefreshTokenRequest struct {
	RefreshToken string `thrift:"refresh_token,1" frugal:"1,default,string" json:"refresh_token"`
}

func NewRefreshTokenRequest() *RefreshTokenRequest {
	return &RefreshTokenRequest{}
}

func (p *RefreshTokenRequest) InitDefault() {
}

func (p *RefreshTokenRequest) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *RefreshTokenRequest) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *RefreshTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenRequest(%+v)", *p)
}

var fieldIDToName_RefreshTokenRequest = map[int16]string{
	1: "refresh_token",
}

type ApiService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *BaseResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *BaseResponse, err error)

	OAuth2Login(ctx context.Context, req *OAuth2LoginRequest) (r *BaseResponse, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (r *BaseResponse, err error)

	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoRequest) (r *BaseResponse, err error)

	ResetPassword(ctx context.Context, req *ResetPasswordRequest) (r *BaseResponse, err error)

	RefreshToken(ctx context.Context, req *RefreshTokenRequest) (r *BaseResponse, err error)
}

type ApiServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewApiServiceRegisterArgs() *ApiServiceRegisterArgs {
	return &ApiServiceRegisterArgs{}
}

func (p *ApiServiceRegisterArgs) InitDefault() {
}

var ApiServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *ApiServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return ApiServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *ApiServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceRegisterArgs = map[int16]string{
	1: "req",
}

type ApiServiceRegisterResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceRegisterResult() *ApiServiceRegisterResult {
	return &ApiServiceRegisterResult{}
}

func (p *ApiServiceRegisterResult) InitDefault() {
}

var ApiServiceRegisterResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceRegisterResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_ApiServiceRegisterResult = map[int16]string{
	0: "success",
}

type ApiServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewApiServiceLoginArgs() *ApiServiceLoginArgs {
	return &ApiServiceLoginArgs{}
}

func (p *ApiServiceLoginArgs) InitDefault() {
}

var ApiServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *ApiServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return ApiServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *ApiServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceLoginArgs = map[int16]string{
	1: "req",
}

type ApiServiceLoginResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceLoginResult() *ApiServiceLoginResult {
	return &ApiServiceLoginResult{}
}

func (p *ApiServiceLoginResult) InitDefault() {
}

var ApiServiceLoginResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceLoginResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceLoginResult(%+v)", *p)
}

var fieldIDToName_ApiServiceLoginResult = map[int16]string{
	0: "success",
}

type ApiServiceOAuth2LoginArgs struct {
	Req *OAuth2LoginRequest `thrift:"req,1" frugal:"1,default,OAuth2LoginRequest" json:"req"`
}

func NewApiServiceOAuth2LoginArgs() *ApiServiceOAuth2LoginArgs {
	return &ApiServiceOAuth2LoginArgs{}
}

func (p *ApiServiceOAuth2LoginArgs) InitDefault() {
}

var ApiServiceOAuth2LoginArgs_Req_DEFAULT *OAuth2LoginRequest

func (p *ApiServiceOAuth2LoginArgs) GetReq() (v *OAuth2LoginRequest) {
	if !p.IsSetReq() {
		return ApiServiceOAuth2LoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceOAuth2LoginArgs) SetReq(val *OAuth2LoginRequest) {
	p.Req = val
}

func (p *ApiServiceOAuth2LoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceOAuth2LoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceOAuth2LoginArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceOAuth2LoginArgs = map[int16]string{
	1: "req",
}

type ApiServiceOAuth2LoginResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceOAuth2LoginResult() *ApiServiceOAuth2LoginResult {
	return &ApiServiceOAuth2LoginResult{}
}

func (p *ApiServiceOAuth2LoginResult) InitDefault() {
}

var ApiServiceOAuth2LoginResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceOAuth2LoginResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceOAuth2LoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceOAuth2LoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceOAuth2LoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceOAuth2LoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceOAuth2LoginResult(%+v)", *p)
}

var fieldIDToName_ApiServiceOAuth2LoginResult = map[int16]string{
	0: "success",
}

type ApiServiceGetUserInfoArgs struct {
	Req *GetUserInfoRequest `thrift:"req,1" frugal:"1,default,GetUserInfoRequest" json:"req"`
}

func NewApiServiceGetUserInfoArgs() *ApiServiceGetUserInfoArgs {
	return &ApiServiceGetUserInfoArgs{}
}

func (p *ApiServiceGetUserInfoArgs) InitDefault() {
}

var ApiServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoRequest

func (p *ApiServiceGetUserInfoArgs) GetReq() (v *GetUserInfoRequest) {
	if !p.IsSetReq() {
		return ApiServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceGetUserInfoArgs) SetReq(val *GetUserInfoRequest) {
	p.Req = val
}

func (p *ApiServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type ApiServiceGetUserInfoResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceGetUserInfoResult() *ApiServiceGetUserInfoResult {
	return &ApiServiceGetUserInfoResult{}
}

func (p *ApiServiceGetUserInfoResult) InitDefault() {
}

var ApiServiceGetUserInfoResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceGetUserInfoResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_ApiServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type ApiServiceUpdateUserInfoArgs struct {
	Req *UpdateUserInfoRequest `thrift:"req,1" frugal:"1,default,UpdateUserInfoRequest" json:"req"`
}

func NewApiServiceUpdateUserInfoArgs() *ApiServiceUpdateUserInfoArgs {
	return &ApiServiceUpdateUserInfoArgs{}
}

func (p *ApiServiceUpdateUserInfoArgs) InitDefault() {
}

var ApiServiceUpdateUserInfoArgs_Req_DEFAULT *UpdateUserInfoRequest

func (p *ApiServiceUpdateUserInfoArgs) GetReq() (v *UpdateUserInfoRequest) {
	if !p.IsSetReq() {
		return ApiServiceUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceUpdateUserInfoArgs) SetReq(val *UpdateUserInfoRequest) {
	p.Req = val
}

func (p *ApiServiceUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type ApiServiceUpdateUserInfoResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceUpdateUserInfoResult() *ApiServiceUpdateUserInfoResult {
	return &ApiServiceUpdateUserInfoResult{}
}

func (p *ApiServiceUpdateUserInfoResult) InitDefault() {
}

var ApiServiceUpdateUserInfoResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceUpdateUserInfoResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_ApiServiceUpdateUserInfoResult = map[int16]string{
	0: "success",
}

type ApiServiceResetPasswordArgs struct {
	Req *ResetPasswordRequest `thrift:"req,1" frugal:"1,default,ResetPasswordRequest" json:"req"`
}

func NewApiServiceResetPasswordArgs() *ApiServiceResetPasswordArgs {
	return &ApiServiceResetPasswordArgs{}
}

func (p *ApiServiceResetPasswordArgs) InitDefault() {
}

var ApiServiceResetPasswordArgs_Req_DEFAULT *ResetPasswordRequest

func (p *ApiServiceResetPasswordArgs) GetReq() (v *ResetPasswordRequest) {
	if !p.IsSetReq() {
		return ApiServiceResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceResetPasswordArgs) SetReq(val *ResetPasswordRequest) {
	p.Req = val
}

func (p *ApiServiceResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceResetPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceResetPasswordArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceResetPasswordArgs = map[int16]string{
	1: "req",
}

type ApiServiceResetPasswordResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceResetPasswordResult() *ApiServiceResetPasswordResult {
	return &ApiServiceResetPasswordResult{}
}

func (p *ApiServiceResetPasswordResult) InitDefault() {
}

var ApiServiceResetPasswordResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceResetPasswordResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceResetPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceResetPasswordResult(%+v)", *p)
}

var fieldIDToName_ApiServiceResetPasswordResult = map[int16]string{
	0: "success",
}

type ApiServiceRefreshTokenArgs struct {
	Req *RefreshTokenRequest `thrift:"req,1" frugal:"1,default,RefreshTokenRequest" json:"req"`
}

func NewApiServiceRefreshTokenArgs() *ApiServiceRefreshTokenArgs {
	return &ApiServiceRefreshTokenArgs{}
}

func (p *ApiServiceRefreshTokenArgs) InitDefault() {
}

var ApiServiceRefreshTokenArgs_Req_DEFAULT *RefreshTokenRequest

func (p *ApiServiceRefreshTokenArgs) GetReq() (v *RefreshTokenRequest) {
	if !p.IsSetReq() {
		return ApiServiceRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ApiServiceRefreshTokenArgs) SetReq(val *RefreshTokenRequest) {
	p.Req = val
}

func (p *ApiServiceRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApiServiceRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceRefreshTokenArgs(%+v)", *p)
}

var fieldIDToName_ApiServiceRefreshTokenArgs = map[int16]string{
	1: "req",
}

type ApiServiceRefreshTokenResult struct {
	Success *BaseResponse `thrift:"success,0,optional" frugal:"0,optional,BaseResponse" json:"success,omitempty"`
}

func NewApiServiceRefreshTokenResult() *ApiServiceRefreshTokenResult {
	return &ApiServiceRefreshTokenResult{}
}

func (p *ApiServiceRefreshTokenResult) InitDefault() {
}

var ApiServiceRefreshTokenResult_Success_DEFAULT *BaseResponse

func (p *ApiServiceRefreshTokenResult) GetSuccess() (v *BaseResponse) {
	if !p.IsSetSuccess() {
		return ApiServiceRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ApiServiceRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResponse)
}

func (p *ApiServiceRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApiServiceRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApiServiceRefreshTokenResult(%+v)", *p)
}

var fieldIDToName_ApiServiceRefreshTokenResult = map[int16]string{
	0: "success",
}
