// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type UserInfo struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username  string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Email     string `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Avatar    string `thrift:"avatar,4" frugal:"4,default,string" json:"avatar"`
	Phone     string `thrift:"phone,5" frugal:"5,default,string" json:"phone"`
	CreatedAt int64  `thrift:"created_at,6" frugal:"6,default,i64" json:"created_at"`
	UpdatedAt int64  `thrift:"updated_at,7" frugal:"7,default,i64" json:"updated_at"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetId() (v int64) {
	return p.Id
}

func (p *UserInfo) GetUsername() (v string) {
	return p.Username
}

func (p *UserInfo) GetEmail() (v string) {
	return p.Email
}

func (p *UserInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UserInfo) GetPhone() (v string) {
	return p.Phone
}

func (p *UserInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *UserInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *UserInfo) SetId(val int64) {
	p.Id = val
}
func (p *UserInfo) SetUsername(val string) {
	p.Username = val
}
func (p *UserInfo) SetEmail(val string) {
	p.Email = val
}
func (p *UserInfo) SetAvatar(val string) {
	p.Avatar = val
}
func (p *UserInfo) SetPhone(val string) {
	p.Phone = val
}
func (p *UserInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *UserInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "id",
	2: "username",
	3: "email",
	4: "avatar",
	5: "phone",
	6: "created_at",
	7: "updated_at",
}

type UserDetail struct {
	BaseInfo *UserInfo `thrift:"base_info,1" frugal:"1,default,UserInfo" json:"base_info"`
	RealName string    `thrift:"real_name,2" frugal:"2,default,string" json:"real_name"`
	Gender   string    `thrift:"gender,3" frugal:"3,default,string" json:"gender"`
	Birthday string    `thrift:"birthday,4" frugal:"4,default,string" json:"birthday"`
	Address  string    `thrift:"address,5" frugal:"5,default,string" json:"address"`
	Bio      string    `thrift:"bio,6" frugal:"6,default,string" json:"bio"`
}

func NewUserDetail() *UserDetail {
	return &UserDetail{}
}

func (p *UserDetail) InitDefault() {
}

var UserDetail_BaseInfo_DEFAULT *UserInfo

func (p *UserDetail) GetBaseInfo() (v *UserInfo) {
	if !p.IsSetBaseInfo() {
		return UserDetail_BaseInfo_DEFAULT
	}
	return p.BaseInfo
}

func (p *UserDetail) GetRealName() (v string) {
	return p.RealName
}

func (p *UserDetail) GetGender() (v string) {
	return p.Gender
}

func (p *UserDetail) GetBirthday() (v string) {
	return p.Birthday
}

func (p *UserDetail) GetAddress() (v string) {
	return p.Address
}

func (p *UserDetail) GetBio() (v string) {
	return p.Bio
}
func (p *UserDetail) SetBaseInfo(val *UserInfo) {
	p.BaseInfo = val
}
func (p *UserDetail) SetRealName(val string) {
	p.RealName = val
}
func (p *UserDetail) SetGender(val string) {
	p.Gender = val
}
func (p *UserDetail) SetBirthday(val string) {
	p.Birthday = val
}
func (p *UserDetail) SetAddress(val string) {
	p.Address = val
}
func (p *UserDetail) SetBio(val string) {
	p.Bio = val
}

func (p *UserDetail) IsSetBaseInfo() bool {
	return p.BaseInfo != nil
}

func (p *UserDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserDetail(%+v)", *p)
}

var fieldIDToName_UserDetail = map[int16]string{
	1: "base_info",
	2: "real_name",
	3: "gender",
	4: "birthday",
	5: "address",
	6: "bio",
}

type RegisterRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Email    string `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Phone    string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterRequest) GetPhone() (v string) {
	return p.Phone
}
func (p *RegisterRequest) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterRequest) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterRequest) SetPhone(val string) {
	p.Phone = val
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "username",
	2: "password",
	3: "email",
	4: "phone",
}

type RegisterResponse struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	UserId  int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

func (p *RegisterResponse) GetCode() (v int32) {
	return p.Code
}

func (p *RegisterResponse) GetMessage() (v string) {
	return p.Message
}

func (p *RegisterResponse) GetUserId() (v int64) {
	return p.UserId
}
func (p *RegisterResponse) SetCode(val int32) {
	p.Code = val
}
func (p *RegisterResponse) SetMessage(val string) {
	p.Message = val
}
func (p *RegisterResponse) SetUserId(val int64) {
	p.UserId = val
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "user_id",
}

type LoginRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "username",
	2: "password",
}

type LoginResponse struct {
	Code      int32     `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message   string    `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Token     string    `thrift:"token,3" frugal:"3,default,string" json:"token"`
	ExpiresIn int64     `thrift:"expires_in,4" frugal:"4,default,i64" json:"expires_in"`
	UserInfo  *UserInfo `thrift:"user_info,5" frugal:"5,default,UserInfo" json:"user_info"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

func (p *LoginResponse) GetCode() (v int32) {
	return p.Code
}

func (p *LoginResponse) GetMessage() (v string) {
	return p.Message
}

func (p *LoginResponse) GetToken() (v string) {
	return p.Token
}

func (p *LoginResponse) GetExpiresIn() (v int64) {
	return p.ExpiresIn
}

var LoginResponse_UserInfo_DEFAULT *UserInfo

func (p *LoginResponse) GetUserInfo() (v *UserInfo) {
	if !p.IsSetUserInfo() {
		return LoginResponse_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LoginResponse) SetCode(val int32) {
	p.Code = val
}
func (p *LoginResponse) SetMessage(val string) {
	p.Message = val
}
func (p *LoginResponse) SetToken(val string) {
	p.Token = val
}
func (p *LoginResponse) SetExpiresIn(val int64) {
	p.ExpiresIn = val
}
func (p *LoginResponse) SetUserInfo(val *UserInfo) {
	p.UserInfo = val
}

func (p *LoginResponse) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "token",
	4: "expires_in",
	5: "user_info",
}

type GetUserInfoRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserInfoRequest() *GetUserInfoRequest {
	return &GetUserInfoRequest{}
}

func (p *GetUserInfoRequest) InitDefault() {
}

func (p *GetUserInfoRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInfoRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoRequest(%+v)", *p)
}

var fieldIDToName_GetUserInfoRequest = map[int16]string{
	1: "user_id",
}

type GetUserInfoResponse struct {
	Code       int32       `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message    string      `thrift:"message,2" frugal:"2,default,string" json:"message"`
	UserDetail *UserDetail `thrift:"user_detail,3" frugal:"3,default,UserDetail" json:"user_detail"`
}

func NewGetUserInfoResponse() *GetUserInfoResponse {
	return &GetUserInfoResponse{}
}

func (p *GetUserInfoResponse) InitDefault() {
}

func (p *GetUserInfoResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetUserInfoResponse) GetMessage() (v string) {
	return p.Message
}

var GetUserInfoResponse_UserDetail_DEFAULT *UserDetail

func (p *GetUserInfoResponse) GetUserDetail() (v *UserDetail) {
	if !p.IsSetUserDetail() {
		return GetUserInfoResponse_UserDetail_DEFAULT
	}
	return p.UserDetail
}
func (p *GetUserInfoResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetUserInfoResponse) SetMessage(val string) {
	p.Message = val
}
func (p *GetUserInfoResponse) SetUserDetail(val *UserDetail) {
	p.UserDetail = val
}

func (p *GetUserInfoResponse) IsSetUserDetail() bool {
	return p.UserDetail != nil
}

func (p *GetUserInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResponse(%+v)", *p)
}

var fieldIDToName_GetUserInfoResponse = map[int16]string{
	1: "code",
	2: "message",
	3: "user_detail",
}

type UpdateUserInfoRequest struct {
	UserId   int64   `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Username *string `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Email    *string `thrift:"email,3,optional" frugal:"3,optional,string" json:"email,omitempty"`
	Phone    *string `thrift:"phone,4,optional" frugal:"4,optional,string" json:"phone,omitempty"`
	Avatar   *string `thrift:"avatar,5,optional" frugal:"5,optional,string" json:"avatar,omitempty"`
	RealName *string `thrift:"real_name,6,optional" frugal:"6,optional,string" json:"real_name,omitempty"`
	Gender   *string `thrift:"gender,7,optional" frugal:"7,optional,string" json:"gender,omitempty"`
	Birthday *string `thrift:"birthday,8,optional" frugal:"8,optional,string" json:"birthday,omitempty"`
	Address  *string `thrift:"address,9,optional" frugal:"9,optional,string" json:"address,omitempty"`
	Bio      *string `thrift:"bio,10,optional" frugal:"10,optional,string" json:"bio,omitempty"`
}

func NewUpdateUserInfoRequest() *UpdateUserInfoRequest {
	return &UpdateUserInfoRequest{}
}

func (p *UpdateUserInfoRequest) InitDefault() {
}

func (p *UpdateUserInfoRequest) GetUserId() (v int64) {
	return p.UserId
}

var UpdateUserInfoRequest_Username_DEFAULT string

func (p *UpdateUserInfoRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UpdateUserInfoRequest_Username_DEFAULT
	}
	return *p.Username
}

var UpdateUserInfoRequest_Email_DEFAULT string

func (p *UpdateUserInfoRequest) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UpdateUserInfoRequest_Email_DEFAULT
	}
	return *p.Email
}

var UpdateUserInfoRequest_Phone_DEFAULT string

func (p *UpdateUserInfoRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UpdateUserInfoRequest_Phone_DEFAULT
	}
	return *p.Phone
}

var UpdateUserInfoRequest_Avatar_DEFAULT string

func (p *UpdateUserInfoRequest) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return UpdateUserInfoRequest_Avatar_DEFAULT
	}
	return *p.Avatar
}

var UpdateUserInfoRequest_RealName_DEFAULT string

func (p *UpdateUserInfoRequest) GetRealName() (v string) {
	if !p.IsSetRealName() {
		return UpdateUserInfoRequest_RealName_DEFAULT
	}
	return *p.RealName
}

var UpdateUserInfoRequest_Gender_DEFAULT string

func (p *UpdateUserInfoRequest) GetGender() (v string) {
	if !p.IsSetGender() {
		return UpdateUserInfoRequest_Gender_DEFAULT
	}
	return *p.Gender
}

var UpdateUserInfoRequest_Birthday_DEFAULT string

func (p *UpdateUserInfoRequest) GetBirthday() (v string) {
	if !p.IsSetBirthday() {
		return UpdateUserInfoRequest_Birthday_DEFAULT
	}
	return *p.Birthday
}

var UpdateUserInfoRequest_Address_DEFAULT string

func (p *UpdateUserInfoRequest) GetAddress() (v string) {
	if !p.IsSetAddress() {
		return UpdateUserInfoRequest_Address_DEFAULT
	}
	return *p.Address
}

var UpdateUserInfoRequest_Bio_DEFAULT string

func (p *UpdateUserInfoRequest) GetBio() (v string) {
	if !p.IsSetBio() {
		return UpdateUserInfoRequest_Bio_DEFAULT
	}
	return *p.Bio
}
func (p *UpdateUserInfoRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateUserInfoRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *UpdateUserInfoRequest) SetEmail(val *string) {
	p.Email = val
}
func (p *UpdateUserInfoRequest) SetPhone(val *string) {
	p.Phone = val
}
func (p *UpdateUserInfoRequest) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *UpdateUserInfoRequest) SetRealName(val *string) {
	p.RealName = val
}
func (p *UpdateUserInfoRequest) SetGender(val *string) {
	p.Gender = val
}
func (p *UpdateUserInfoRequest) SetBirthday(val *string) {
	p.Birthday = val
}
func (p *UpdateUserInfoRequest) SetAddress(val *string) {
	p.Address = val
}
func (p *UpdateUserInfoRequest) SetBio(val *string) {
	p.Bio = val
}

func (p *UpdateUserInfoRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UpdateUserInfoRequest) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UpdateUserInfoRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UpdateUserInfoRequest) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *UpdateUserInfoRequest) IsSetRealName() bool {
	return p.RealName != nil
}

func (p *UpdateUserInfoRequest) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UpdateUserInfoRequest) IsSetBirthday() bool {
	return p.Birthday != nil
}

func (p *UpdateUserInfoRequest) IsSetAddress() bool {
	return p.Address != nil
}

func (p *UpdateUserInfoRequest) IsSetBio() bool {
	return p.Bio != nil
}

func (p *UpdateUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoRequest = map[int16]string{
	1:  "user_id",
	2:  "username",
	3:  "email",
	4:  "phone",
	5:  "avatar",
	6:  "real_name",
	7:  "gender",
	8:  "birthday",
	9:  "address",
	10: "bio",
}

type UpdateUserInfoResponse struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewUpdateUserInfoResponse() *UpdateUserInfoResponse {
	return &UpdateUserInfoResponse{}
}

func (p *UpdateUserInfoResponse) InitDefault() {
}

func (p *UpdateUserInfoResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UpdateUserInfoResponse) GetMessage() (v string) {
	return p.Message
}
func (p *UpdateUserInfoResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UpdateUserInfoResponse) SetMessage(val string) {
	p.Message = val
}

func (p *UpdateUserInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoResponse(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoResponse = map[int16]string{
	1: "code",
	2: "message",
}

type ResetPasswordRequest struct {
	UserId       int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	OldPassword  string `thrift:"old_password,2" frugal:"2,default,string" json:"old_password"`
	NewPassword_ string `thrift:"new_password,3" frugal:"3,default,string" json:"new_password"`
}

func NewResetPasswordRequest() *ResetPasswordRequest {
	return &ResetPasswordRequest{}
}

func (p *ResetPasswordRequest) InitDefault() {
}

func (p *ResetPasswordRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ResetPasswordRequest) GetOldPassword() (v string) {
	return p.OldPassword
}

func (p *ResetPasswordRequest) GetNewPassword_() (v string) {
	return p.NewPassword_
}
func (p *ResetPasswordRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ResetPasswordRequest) SetOldPassword(val string) {
	p.OldPassword = val
}
func (p *ResetPasswordRequest) SetNewPassword_(val string) {
	p.NewPassword_ = val
}

func (p *ResetPasswordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordRequest(%+v)", *p)
}

var fieldIDToName_ResetPasswordRequest = map[int16]string{
	1: "user_id",
	2: "old_password",
	3: "new_password",
}

type ResetPasswordResponse struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewResetPasswordResponse() *ResetPasswordResponse {
	return &ResetPasswordResponse{}
}

func (p *ResetPasswordResponse) InitDefault() {
}

func (p *ResetPasswordResponse) GetCode() (v int32) {
	return p.Code
}

func (p *ResetPasswordResponse) GetMessage() (v string) {
	return p.Message
}
func (p *ResetPasswordResponse) SetCode(val int32) {
	p.Code = val
}
func (p *ResetPasswordResponse) SetMessage(val string) {
	p.Message = val
}

func (p *ResetPasswordResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordResponse(%+v)", *p)
}

var fieldIDToName_ResetPasswordResponse = map[int16]string{
	1: "code",
	2: "message",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (r *GetUserInfoResponse, err error)

	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoRequest) (r *UpdateUserInfoResponse, err error)

	ResetPassword(ctx context.Context, req *ResetPasswordRequest) (r *ResetPasswordResponse, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoRequest `thrift:"req,1" frugal:"1,default,GetUserInfoRequest" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoRequest

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoRequest) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResponse

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResponse)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserInfoArgs struct {
	Req *UpdateUserInfoRequest `thrift:"req,1" frugal:"1,default,UpdateUserInfoRequest" json:"req"`
}

func NewUserServiceUpdateUserInfoArgs() *UserServiceUpdateUserInfoArgs {
	return &UserServiceUpdateUserInfoArgs{}
}

func (p *UserServiceUpdateUserInfoArgs) InitDefault() {
}

var UserServiceUpdateUserInfoArgs_Req_DEFAULT *UpdateUserInfoRequest

func (p *UserServiceUpdateUserInfoArgs) GetReq() (v *UpdateUserInfoRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserInfoArgs) SetReq(val *UpdateUserInfoRequest) {
	p.Req = val
}

func (p *UserServiceUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserInfoResult struct {
	Success *UpdateUserInfoResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInfoResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateUserInfoResult() *UserServiceUpdateUserInfoResult {
	return &UserServiceUpdateUserInfoResult{}
}

func (p *UserServiceUpdateUserInfoResult) InitDefault() {
}

var UserServiceUpdateUserInfoResult_Success_DEFAULT *UpdateUserInfoResponse

func (p *UserServiceUpdateUserInfoResult) GetSuccess() (v *UpdateUserInfoResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInfoResponse)
}

func (p *UserServiceUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceResetPasswordArgs struct {
	Req *ResetPasswordRequest `thrift:"req,1" frugal:"1,default,ResetPasswordRequest" json:"req"`
}

func NewUserServiceResetPasswordArgs() *UserServiceResetPasswordArgs {
	return &UserServiceResetPasswordArgs{}
}

func (p *UserServiceResetPasswordArgs) InitDefault() {
}

var UserServiceResetPasswordArgs_Req_DEFAULT *ResetPasswordRequest

func (p *UserServiceResetPasswordArgs) GetReq() (v *ResetPasswordRequest) {
	if !p.IsSetReq() {
		return UserServiceResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceResetPasswordArgs) SetReq(val *ResetPasswordRequest) {
	p.Req = val
}

func (p *UserServiceResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceResetPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceResetPasswordResult struct {
	Success *ResetPasswordResponse `thrift:"success,0,optional" frugal:"0,optional,ResetPasswordResponse" json:"success,omitempty"`
}

func NewUserServiceResetPasswordResult() *UserServiceResetPasswordResult {
	return &UserServiceResetPasswordResult{}
}

func (p *UserServiceResetPasswordResult) InitDefault() {
}

var UserServiceResetPasswordResult_Success_DEFAULT *ResetPasswordResponse

func (p *UserServiceResetPasswordResult) GetSuccess() (v *ResetPasswordResponse) {
	if !p.IsSetSuccess() {
		return UserServiceResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*ResetPasswordResponse)
}

func (p *UserServiceResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceResetPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordResult = map[int16]string{
	0: "success",
}
