// Code generated by Kitex v0.13.1. DO NOT EDIT.

package authservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	auth "user_service/api/kitex_gen/auth"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ValidateToken": kitex.NewMethodInfo(
		validateTokenHandler,
		newAuthServiceValidateTokenArgs,
		newAuthServiceValidateTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newAuthServiceRefreshTokenArgs,
		newAuthServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OAuth2Login": kitex.NewMethodInfo(
		oAuth2LoginHandler,
		newAuthServiceOAuth2LoginArgs,
		newAuthServiceOAuth2LoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName":     "auth",
		"ServiceFilePath": `D:\GoProj\user_service\api\idl\auth.thrift`,
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func validateTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceValidateTokenArgs)
	realResult := result.(*auth.AuthServiceValidateTokenResult)
	success, err := handler.(auth.AuthService).ValidateToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceValidateTokenArgs() interface{} {
	return auth.NewAuthServiceValidateTokenArgs()
}

func newAuthServiceValidateTokenResult() interface{} {
	return auth.NewAuthServiceValidateTokenResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceRefreshTokenArgs)
	realResult := result.(*auth.AuthServiceRefreshTokenResult)
	success, err := handler.(auth.AuthService).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceRefreshTokenArgs() interface{} {
	return auth.NewAuthServiceRefreshTokenArgs()
}

func newAuthServiceRefreshTokenResult() interface{} {
	return auth.NewAuthServiceRefreshTokenResult()
}

func oAuth2LoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceOAuth2LoginArgs)
	realResult := result.(*auth.AuthServiceOAuth2LoginResult)
	success, err := handler.(auth.AuthService).OAuth2Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceOAuth2LoginArgs() interface{} {
	return auth.NewAuthServiceOAuth2LoginArgs()
}

func newAuthServiceOAuth2LoginResult() interface{} {
	return auth.NewAuthServiceOAuth2LoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ValidateToken(ctx context.Context, req *auth.ValidateTokenRequest) (r *auth.ValidateTokenResponse, err error) {
	var _args auth.AuthServiceValidateTokenArgs
	_args.Req = req
	var _result auth.AuthServiceValidateTokenResult
	if err = p.c.Call(ctx, "ValidateToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *auth.RefreshTokenRequest) (r *auth.RefreshTokenResponse, err error) {
	var _args auth.AuthServiceRefreshTokenArgs
	_args.Req = req
	var _result auth.AuthServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OAuth2Login(ctx context.Context, req *auth.OAuth2LoginRequest) (r *auth.OAuth2LoginResponse, err error) {
	var _args auth.AuthServiceOAuth2LoginArgs
	_args.Req = req
	var _result auth.AuthServiceOAuth2LoginResult
	if err = p.c.Call(ctx, "OAuth2Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
